name: etl
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - boto3=1.24.28
  - botocore=1.27.59
  - brotlipy=0.7.0
  - ca-certificates=2023.05.30
  - certifi=2023.5.7
  - cffi=1.15.1
  - cryptography=39.0.1
  - idna=3.4
  - jmespath=0.10.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.9
  - pip=23.1.2
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - readline=8.2
  - s3transfer=0.6.0
  - setuptools=67.8.0
  - six=1.16.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - urllib3=1.26.16
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
    - charset-normalizer==3.1.0
    - requests==2.31.0